### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by arnaudcourtecuisse** [inmogr/node-ts-mask-phone-number#1]
Hi, I was interested in the functionality, but it's not clear how the number is formatted. Could you improve the documentation ? Thanks !

**Comment by inmogr** [comment]
Hi, thanks for reaching out :)
I'll definitely add some description this weekend or next weekend at most but for now just to give you simple description. this library checks the validation of the phone number first and the number must have international code for example USA international code is "+1" or "001". If the number is valid all digits will be replaced with "*" except last 4 digits will be displayed as is.

**Comment by inmogr** [comment]
Hi,

Updated kindly look at it :)
https://github.com/inmogr/node-ts-mask-phone-number/commit/513263c537a01d32578eca91e3e7df4f892c938d

**Comment by arnaudcourtecuisse** [comment]
That's perfect, thanks !
